site_name: "Azure Data Lake Ingestion Project 2"
site_description: "Documentation for setting up Azure Data Lake Gen2 and managing data ingestion from various sources."
site_url: https://DaiTensa.github.io/Azure_Data_Lake_Security/
theme:
  name: "material"  # Optional: Choose a theme you like (e.g., 'readthedocs' or 'material')
  palette:
    primary: "blue"
    accent: "light blue"
  font:
    text: "Roboto"
    code: "Roboto Mono"
nav:
  - Accueil: index.md
  - Partie 01 Veille systèmes de Sécurité: 
    - Introduction: partie1/introduction.md
    - Veille systèmes de sécurité: partie1/veille.md
    - Structure projet: partie1/structure.md
  - Partie 02 Création et ingestion sécurisée sur le data lake: 
    - Introduction: partie2/introduction.md
    - Déploiement Terraform: partie2/deploiement.md
    - Sécurité: partie2/security.md
    - Ingestion des données : partie2/ingestion.md
    - Infrastructure: partie2/infrastructure.md
  - Partie 03 Configuration d'Azure Databricks: 
    - Introduction: partie3/introduction.md
    - Déploiement Terraform: partie3/deploiement.md
    - Sécurité: partie3/securite.md
plugins:
  - search